services:
  database:
    image: __IMAGE_NAMESPACE__-database
    hostname: database
    build:
      context: ./database
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aktin-network
  wildfly:
    image: __IMAGE_NAMESPACE__-wildfly
    hostname: wildfly
    build:
      context: ./wildfly
    environment:
      DB_HOST: database
      DB_PORT: 5432
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Dfile.encoding=UTF-8
    volumes:
      - aktin_config:/etc/aktin
      - aktin_data:/var/lib/aktin
    expose:
      - "8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - aktin-network
  httpd:
    image: __IMAGE_NAMESPACE__-httpd
    hostname: httpd
    build:
      context: ./httpd
    ports:
      - "80:80"
    depends_on:
      - wildfly
    networks:
      - aktin-network

volumes:
  pg_data:
    driver: local
  aktin_config:
    driver: local
    driver_opts:
      o: uid=wildfly,gid=wildfly
  aktin_data:
    driver: local
    driver_opts:
      o: uid=wildfly,gid=wildfly

networks:
  aktin-network:
    driver: bridge
