# --------------------------------------
# Script Name:  compose.yml
# Author:       shuening@ukaachen.de, skurka@ukaachen.de, akombeiz@ukaachen.de
# Purpose:      Defines AKTIN emergency department system services:
#               - PostgreSQL database with i2b2/AKTIN schema
#               - WildFly application server
#               - Apache2 reverse proxy with i2b2 webclient
# --------------------------------------

name: ${PROJECT_NAME:-build}
services:
  database:
    image: __IMAGE_NAMESPACE__-database:__DWH_GITHUB_TAG__-docker__DATABASE_CONTAINER_VERSION__
    hostname: database
    build:
      context: ./database
      args:
        BUILD_TIME: "${BUILD_TIME}"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aktin-network
  wildfly:
    image: __IMAGE_NAMESPACE__-wildfly:__DWH_GITHUB_TAG__-docker__WILDFLY_CONTAINER_VERSION__
    hostname: wildfly
    build:
      context: ./wildfly
      args:
        BUILD_TIME: "${BUILD_TIME}"
    environment:
      DB_HOST: database
      DB_PORT: 5432
    volumes:
      - aktin_config:/etc/aktin
      - aktin_data:/var/lib/aktin
    expose:
      - "8080"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/broker/status" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aktin-network
  httpd:
    image: __IMAGE_NAMESPACE__-httpd:__DWH_GITHUB_TAG__-docker__HTTPD_CONTAINER_VERSION__
    hostname: httpd
    build:
      context: ./httpd
      args:
        BUILD_TIME: "${BUILD_TIME}"
    ports:
      - "${HTTP_PORT:-80}:80"
    depends_on:
      - wildfly
    healthcheck:
      test: [ "CMD", "apache2ctl", "configtest" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aktin-network

volumes:
  pg_data:
    driver: local
  aktin_config:
    driver: local
  aktin_data:
    driver: local

networks:
  aktin-network:
    driver: bridge
