# --------------------------------------
# Script Name:  compose.yml
# Author:       shuening@ukaachen.de, skurka@ukaachen.de, akombeiz@ukaachen.de
# Purpose:      Defines AKTIN emergency department system services:
#               - PostgreSQL database with i2b2/AKTIN schema
#               - WildFly application server
#               - Apache2 reverse proxy with i2b2 webclient
# --------------------------------------

services:
  database:
    image: __IMAGE_NAMESPACE__-database:__DWH_GITHUB_TAG__-docker__DATABASE_CONTAINER_VERSION__
    hostname: database
    restart: unless-stopped
    build:
      context: ./database
      args:
        BUILD_TIME: "${BUILD_TIME}"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres && psql -U postgres -d aktin -c \"SELECT 1 FROM information_schema.schemata WHERE schema_name = 'aktin'\"" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 180s
    networks:
      - aktin-network
  wildfly:
    image: __IMAGE_NAMESPACE__-wildfly:__DWH_GITHUB_TAG__-docker__WILDFLY_CONTAINER_VERSION__
    hostname: wildfly
    restart: unless-stopped
    build:
      context: ./wildfly
      args:
        BUILD_TIME: "${BUILD_TIME}"
    environment:
      DB_HOST: database
      DB_PORT: 5432
    volumes:
      - aktin_config:/etc/aktin
      - aktin_data:/var/lib/aktin
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget --server-response --spider http://127.0.0.1:9090/aktin/admin/rest/info/version 2>&1 | awk '/^  HTTP/{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - aktin-network
  httpd:
    image: __IMAGE_NAMESPACE__-httpd:__DWH_GITHUB_TAG__-docker__HTTPD_CONTAINER_VERSION__
    hostname: httpd
    restart: unless-stopped
    build:
      context: ./httpd
      args:
        BUILD_TIME: "${BUILD_TIME}"
    ports:
      - "${HTTP_PORT:-80}:80"
    depends_on:
      - wildfly
    healthcheck:
      test: [ "CMD", "apache2ctl", "configtest" ]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - aktin-network

volumes:
  pg_data:
    driver: local
  aktin_config:
    driver: local
  aktin_data:
    driver: local

networks:
  aktin-network:
    driver: bridge
