name: Setup AKTIN Environment
description: Set up Java and Maven environment

runs:
  using: composite
  steps:
    - name: Setup Java
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: temurin
        java-version: '21'

    - name: Install Maven
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y maven
