name: AKTIN Build Docker

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        default: 'dockerfiles'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Cache Name
        run: echo "CACHE=${sort versions | awk '!/(^[[:space:]]*$|DWH_GITHUB_TAG=|_CONTAINER_VERSION=|#)/' ORS='--'}" >> $GITHUB_ENV
        working-directory: src/docker

      - name: Retrieve Cached Downloads
        uses: actions/cache@v4
        with:
          path: src/downloads/
          key: downloads--${{ env.CACHE }}

      - name: Build Dockerfiles
        run: build.sh
        working-directory: src/docker

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            src/build
            !src/build/compose.yml
          if-no-files-found: 'error'