name: Build and Deploy Docker Images

on:
  workflow_call:
    inputs:
      cache_key:
        description: "Cache key for retrieving pre-downloaded dependencies"
        required: true
        type: string
    secrets:
      DEV_API_KEY:
        description: "API key used for Wildfly DEV_MODE"
        required: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Install cosign
        uses: sigstore/cosign-installer@d58896d6a1865668819e1d91763c7751a165e159 # v3.9.2

      - name: Restore cached downloads
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: src/downloads/
          key: ${{ inputs.cache_key }}

      - name: Build Docker images
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
        working-directory: src
        run: ./build.sh --create-latest

      - name: Login to GHCR
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy and sign images
        id: deploy-sign
        run: |
          set -euo pipefail
          for SERVICE in database wildfly httpd; do
            IMAGE="ghcr.io/aktin/notaufnahme-dwh-${SERVICE}"
            docker push --all-tags "$IMAGE"
            # capture the registry digest for :latest and sign ONLY that
            # pushing :latest again is very cheap because of content-addressable layers in ghcr
            LATEST_DIGEST="$(docker push "${IMAGE}:latest" | grep -Eo 'sha256:[0-9a-f]{64}' | tail -n1)"
            if [[ -z "$LATEST_DIGEST" ]]; then
              echo "Failed to resolve digest for ${IMAGE}:latest" >&2
              exit 1
            fi
            cosign sign --yes "${IMAGE}@${LATEST_DIGEST}"
          done

      - name: Upload compose artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: compose-yml
          path: src/build/compose.yml
          if-no-files-found: error
          retention-days: 1
