name: Build AKTIN Docker Images

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        default: 'dockerfiles'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Cache Name
        run: echo "CACHE=$(sort versions | awk '!/(^[[:space:]]*$|DWH_GITHUB_TAG=|_CONTAINER_VERSION=|#)/' ORS='--')" >> $GITHUB_ENV
        working-directory: src/docker

      - name: Retrieve Cached Downloads
        uses: actions/cache@v4
        with:
          path: src/downloads/
          key: downloads--${{ env.CACHE }}

      - name: Build Dockerfiles
        run: build.sh --create-latest
        working-directory: src

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Dockerfiles
        run: docker compose -f compose.yml push
        working-directory: src/build

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: src/build/compose.yml
          fail_on_unmatched_files: true
          make_latest: true
