name: CI/CD Docker

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+**

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
