name: AKTIN Deploy Docker

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        default: 'dockerfiles'
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG_BASE: ghcr.io/aktin/notaufnahme-dwh
    steps:
      - name: Prepare Version Variable
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image for ${{ github.job }} [httpd]
        uses: docker/build-push-action@v6
        with:
          context: httpd/
          tags: |
            ${{ env.TAG_BASE }}-httpd:latest
            ${{ env.TAG_BASE }}-httpd:$VERSION
          push: true

      - name: Build and push docker image for ${{ github.job }} [database]
        uses: docker/build-push-action@v6
        with:
          context: database/
          tags: |
            ${{ env.TAG_BASE }}-database:latest
            ${{ env.TAG_BASE }}-database:$VERSION
          push: true

      - name: Build and push docker image for ${{ github.job }} [wildfly]
        uses: docker/build-push-action@v6
        with:
          context: wildfly/
          tags: |
            ${{ env.TAG_BASE }}-wildfly:latest
            ${{ env.TAG_BASE }}-wildfly:$VERSION
          push: true
