name: AKTIN Deploy Docker

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Name of the artifact to download'
        default: 'dockerfiles'
        type: string
      tag-base:
        description: 'Prefix of the docker tags (either ghcr.io/aktin/notaufnahme-i2b2 or ghcr.io/aktin/notaufnahme-dwh)'
        required: true
        type: string


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Prepare Version Variable
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image for ${{ github.job }} [httpd]
        uses: docker/build-push-action@v6
        with:
          context: httpd/
          tags: |
            ${{ inputs.tag-base }}-httpd:latest
            ${{ inputs.tag-base }}-httpd:$VERSION
          push: true

      - name: Build and push docker image for ${{ github.job }} [database]
        uses: docker/build-push-action@v6
        with:
          context: database/
          tags: |
            ${{ inputs.tag-base }}-database:latest
            ${{ inputs.tag-base }}-database:$VERSION
          push: true

      - name: Build and push docker image for ${{ github.job }} [wildfly]
        uses: docker/build-push-action@v6
        with:
          context: wildfly/
          tags: |
            ${{ inputs.tag-base }}-wildfly:latest
            ${{ inputs.tag-base }}-wildfly:$VERSION
          push: true
