name: Create new Docker Release

on:
  push:
    tags:
      - v[0-9]+.[0-9]+**

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      cache_key: ${{ steps.cache.outputs.cache_key }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Cache Name
        run: |
          CACHE=$(sort versions | awk '!/(^[[:space:]]*$|DWH_GITHUB_TAG=|_CONTAINER_VERSION=|#)/' ORS='--')
          echo "cache_key=downloads--$CACHE" >> $GITHUB_OUTPUT
        working-directory: src/docker

  build-and-deploy:
    needs: prepare
    uses: ./.github/workflows/build-deploy-docker.yml
    with:
      cache_key: ${{ needs.prepare.outputs.cache_key }}
    secrets:
      DEV_API_KEY: ${{ secrets.DEV_API_KEY }}

  release:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/build/compose.yml
          body_path: .github/release_notes.md
          fail_on_unmatched_files: true
          make_latest: true
