name: Deploy Base Container Security Updates

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  prepare:
    uses: ./.github/workflows/prepare-cache.yml

  check-postgres:
    needs: [prepare]
    uses: ./.github/workflows/check-container-update.yml
    with:
      container: postgres
      version_key: POSTGRESQL_VERSION

  check-ubuntu:
    needs: [check-postgres]
    uses: ./.github/workflows/check-container-update.yml
    with:
      container: ubuntu
      version_key: UBUNTU_VERSION

  check-php:
    needs: [check-ubuntu]
    uses: ./.github/workflows/check-container-update.yml
    with:
      container: php
      version_key: APACHE_VERSION

  build-and-deploy:
    needs: [prepare, check-postgres, check-ubuntu, check-php]
    if: |
      needs.check-postgres.outputs.update == 'true' ||
      needs.check-ubuntu.outputs.update == 'true' ||
      needs.check-php.outputs.update == 'true'
    uses: ./.github/workflows/build-deploy-docker.yml
    with:
      cache_key: ${{ needs.prepare.outputs.cache_key }}
    secrets:
      DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
